version: 0.2
phases:
  pre_build:
    commands:
      - echo $AWS_DEFAULT_REGION
      - echo $URL
  build: 
    steps:
      - uses: liquibase-github-actions/update@v4.21.1
        with:
          changelogFile: changelog-root.xml
          url: database-1-instance-1.c1jnktys7ztt.us-east-1.rds.amazonaws.com
          username: postgres
          password: Akshay123
          headless: true
